apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  - routes.yaml
labels:
  - pairs:
      app.kubernetes.io/name: garage
    includeSelectors: true
