apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: garage-s3
spec:
  host: garage-s3.apps.majora.home.lab
  to:
    kind: Service
    name: garage
    weight: 100
  port:
    targetPort: 3900
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: garage-admin
spec:
  host: garage-admin.apps.majora.home.lab
  to:
    kind: Service
    name: garage
    weight: 100
  port:
    targetPort: 3903
  wildcardPolicy: None
