kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: esphome-config
  labels:
    app.kubernetes.io/name: esphome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 1Gi
