apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quay-metrics.service.yaml
  - quay-metrics.role.yaml
  - quay-metrics.rolebinding.yaml
  - quay-metrics.servicemonitor.yaml
  - quay-grafana-dashboard.configmap.yaml
  - quay-alerts.role.yaml
  - quay-alerts.rolebinding.yaml
  - quay-alerts.prometheusrule.yaml
