apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - buildconfig-dev.yaml
  - rbac.yaml
  - configmap-state.yaml
  - cronjob-git-poll.yaml
  - scc.yaml
