apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/tags/v1.92.3/cmd/k8s-operator/deploy/manifests/operator.yaml
  - scc.yaml
patches:
  - path: secret.yaml
  - path: deployment-patch.yaml
images:
  - name: tailscale/k8s-operator
    newName: ghcr.io/tailscale/k8s-operator
    newTag: v1.92.3
