apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      unit_system: metric
      time_zone: America/New_York

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.128.0.0/14
        - 10.244.0.0/16
        - 127.0.0.1

    default_config:

    automation:
      - alias: "Daily Backup"
        trigger:
          - platform: time
            at: "03:00:00"
        action:
          - service: backup.create
