apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - quay-deployment.yaml
  - quay-service.yaml
  - route.yaml
