apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - routes.yaml
  - service.yaml
  - tailscale-ingress.yaml
