apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app.kubernetes.io/name: frigate
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frigate
  ports:
    - name: frigate
      port: 5000
      targetPort: 5000
    - name: go2rtc
      port: 1984
      targetPort: 1984
